version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MODAL_ENDPOINT_URL=${MODAL_ENDPOINT_URL}
      - MODAL_API_KEY=${MODAL_API_KEY}
      - SUPABASE_PROJECT_ID=${SUPABASE_PROJECT_ID}
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
    volumes:
      - ./backend:/app
    depends_on:
      - modal

  modal:
    build:
      context: ./modal-service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - UVICORN_RELOAD=true
    volumes:
      - ./modal-service:/app
