services:
  - type: web
    name: mimetic-demo-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: MODAL_ENDPOINT_URL
        sync: false
      - key: MODAL_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: USE_MOCK_MODAL
        value: "false"
      - key: CORS_ORIGINS
        value: "https://mimetic-demo*.vercel.app"
      - key: LOG_LEVEL
        value: info
