name: Validate Modal Services

on:
  pull_request:
    branches: [main]
    paths:
      - 'modal-service/**'
  push:
    branches:
      - 'feature/**'
      - 'dev/**'
    paths:
      - 'modal-service/**'

jobs:
  validate:
    name: Validate Modal Code
    runs-on: ubuntu-latest
    environment: preview  # Use preview environment
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install modal
          cd modal-service
          pip install -r requirements.txt

      - name: Authenticate with Modal
        run: |
          modal token set --token-id ${{ secrets.MODAL_TOKEN_ID }} --token-secret ${{ secrets.MODAL_TOKEN_SECRET }}
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}

      - name: Validate Modal services
        run: |
          cd modal-service
          echo "Validating main service..."
          modal app validate modal_service.py
          
          if [ -f "webrtc_service.py" ]; then
            echo "Validating WebRTC service..."
            modal app validate webrtc_service.py
          fi

      - name: Syntax check
        run: |
          cd modal-service
          python -m py_compile modal_service.py
          
          if [ -f "webrtc_service.py" ]; then
            python -m py_compile webrtc_service.py
          fi

      - name: Validation Success
        run: |
          echo "✅ All Modal services validated successfully!"
          echo "Ready for deployment when merged to main."
